'use client';

import type { SiteData } from '@/lib/domain';
import styles from './admin.module.css';

export function ContentEditor({data,onChange}:{data:SiteData;onChange:(next:Partial<SiteData>)=>void}){
  const hero=(key:keyof SiteData['hero'],value:string)=>onChange({hero:{...data.hero,[key]:value}});
  return <section className={styles.panel}><div className={styles.sectionHeader}><div><span className="rafay-kicker">Public copy</span><h1 className="rafay-display">Website Content</h1></div></div><h3 className={styles.subhead}>Hero</h3><div className={styles.fieldGrid}><Field label="Eyebrow"><input value={data.hero.eyebrow} onChange={(e)=>hero('eyebrow',e.target.value)}/></Field><Field label="Heading"><input value={data.hero.heading} onChange={(e)=>hero('heading',e.target.value)}/></Field><Field label="Body"><textarea value={data.hero.body} onChange={(e)=>hero('body',e.target.value)}/></Field><Field label="Primary CTA"><input value={data.hero.primaryCta} onChange={(e)=>hero('primaryCta',e.target.value)}/></Field><Field label="Secondary CTA"><input value={data.hero.secondaryCta} onChange={(e)=>hero('secondaryCta',e.target.value)}/></Field></div><h3 className={styles.subhead}>Trust cards</h3>{data.trustCards.map((card,index)=><div className={styles.inlineCard} key={card.id}><input value={card.title} onChange={(e)=>onChange({trustCards:data.trustCards.map((item,i)=>i===index?{...item,title:e.target.value}:item)})}/><textarea value={card.text} onChange={(e)=>onChange({trustCards:data.trustCards.map((item,i)=>i===index?{...item,text:e.target.value}:item)})}/></div>)}<h3 className={styles.subhead}>How it works</h3>{data.howItWorks.map((card,index)=><div className={styles.inlineCard} key={card.id}><input value={card.title} onChange={(e)=>onChange({howItWorks:data.howItWorks.map((item,i)=>i===index?{...item,title:e.target.value}:item)})}/><textarea value={card.text} onChange={(e)=>onChange({howItWorks:data.howItWorks.map((item,i)=>i===index?{...item,text:e.target.value}:item)})}/></div>)}<div className={styles.fieldGrid}><Field label="Footer"><textarea value={data.footer} onChange={(e)=>onChange({footer:e.target.value})}/></Field><Field label="Legal / consent notice"><textarea value={data.legalNotice} onChange={(e)=>onChange({legalNotice:e.target.value})}/></Field></div></section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}><span>{label}</span>{children}</label>}
