'use client';

import type { Profile } from '@/lib/domain';
import { canPublishProfile } from './admin-client';
import styles from './admin.module.css';

export function ProfileEditor({profile,onChange,onDelete,onMoveUp,onMoveDown}:{profile:Profile;onChange:(profile:Profile)=>void;onDelete:()=>void;onMoveUp:()=>void;onMoveDown:()=>void}){
  const setActive=(active:boolean)=>{ if(active&&!canPublishProfile(profile)){ alert('Add name, label and bio and keep adult confirmation enabled before publishing.'); return; } onChange({...profile,active}); };
  return <article className={styles.editorCard}><div className={styles.rowBetween}><div><span className="rafay-kicker">Profile {profile.displayOrder+1}</span><h3>{profile.name||'Untitled profile'}</h3></div><div className={styles.miniActions}><button className={styles.smallButton} onClick={onMoveUp}>↑</button><button className={styles.smallButton} onClick={onMoveDown}>↓</button><button className={styles.danger} onClick={onDelete}>Delete</button></div></div><div className={styles.fieldGrid}><Field label="Name"><input value={profile.name} maxLength={80} onChange={(e)=>onChange({...profile,name:e.target.value})}/></Field><Field label="Short label"><input value={profile.label} maxLength={80} onChange={(e)=>onChange({...profile,label:e.target.value})}/></Field><Field label="Bio"><textarea value={profile.bio} maxLength={1200} onChange={(e)=>onChange({...profile,bio:e.target.value})}/></Field><Field label="Tags (comma separated)"><input value={profile.tags.join(', ')} onChange={(e)=>onChange({...profile,tags:e.target.value.split(',').map((tag)=>tag.trim()).filter(Boolean).slice(0,12)})}/></Field><Field label="Availability note"><input value={profile.availabilityNote} maxLength={300} onChange={(e)=>onChange({...profile,availabilityNote:e.target.value})}/></Field></div><div className={styles.toggleRow}><label className={styles.toggle}><input type="checkbox" checked={profile.adultConfirmed} onChange={(e)=>onChange({...profile,adultConfirmed:e.target.checked,active:e.target.checked?profile.active:false})}/> Adult confirmed (18+)</label><label className={styles.toggle}><input type="checkbox" checked={profile.active} onChange={(e)=>setActive(e.target.checked)}/> Published</label></div><div className={styles.imageStub}>{profile.images.length ? `${profile.images.length} image(s) linked` : 'Image manager connects in Media task.'}</div></article>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}><span>{label}</span>{children}</label>}
